<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,1,1,'5paw6Ze76LWE6K6v');
$cfg_Cs[3]=array(0,1,1,'5Lqn5ZOB5bGV56S6');
$cfg_Cs[4]=array(0,1,1,'6I2j6KqJ6LWE6LSo');
$cfg_Cs[5]=array(0,1,1,'5pyN5Yqh6aG555uu');
$cfg_Cs[6]=array(0,1,1,'5Zyo57q/55WZ6KiA');
$cfg_Cs[7]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[8]=array(2,1,1,'5YWs5Y+45paw6Ze7');
$cfg_Cs[9]=array(2,1,1,'6KGM5Lia5Yqo5oCB');
$cfg_Cs[10]=array(3,1,1,'5Lqn5ZOB5LiA57G7');
$cfg_Cs[11]=array(3,1,1,'5Lqn5ZOB5LqM57G7');
$cfg_Cs[12]=array(3,1,1,'5Lqn5ZOB5LiJ57G7');
$cfg_Cs[13]=array(3,1,1,'5Lqn5ZOB5Zub57G7');
?>