<?php
$z[0]=Array("flink","\r\n[field:link /]\r\n",147,192);
$z[1]=Array("global","",290,317);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("channel","\r\n<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n",340,434);
$z[2][4]['type']="top";
$z[3]=Array("global","",478,500);
$z[3][4]['name']="cfg_add";
$z[4]=Array("global","",535,557);
$z[4][4]['name']="cfg_tel";
$z[5]=Array("global","",589,610);
$z[5][4]['name']="cfg_qq";
$z[6]=Array("global","",633,659);
$z[6][4]['name']="cfg_powerby";
$z[7]=Array("global","",804,828);
$z[7][4]['name']="cfg_beian";

?>