<?php
$z[0]=Array("global","",74,101);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",174,200);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",275,302);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("channelartlist","\r\n<li><a href=\"{dede:field name='typeurl'/}\"   class=\"{dede:field.currentstyle/}\">{dede:field name='typename'/}</a>\r\n<div class=\"nav\"> \r\n{dede:channel type='son' noself='yes' }\r\n<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n{/dede:channel}\r\n</div>\r\n</li>\r\n",329,676);
$z[3][4]['typeid']="top";
$z[3][4]['row']="7";
$z[3][4]['currentstyle']="cur";
$z[4]=Array("sql"," \r\n<li style=\"background:url('[field:pic/]') no-repeat center top\"></li>\r\n",783,956);
$z[4][4]['sql']="select * from #@__flash where ischeck=2 order by sortrank asc limit 0,4";
$z[5]=Array("global","",1181,1207);
$z[5][4]['name']="cfg_gonggao";

?>